### ISSUE TITLE
Non hai documentación.

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Music#11]
O proxecto non inclúe documentación: apenas hai comentarios en JavaDoc no código fonte, e tampouco hai ningún diagrama UML que represente a estrutura actual da implementación (a evolución do diagrama do enunciado incluído no README).

**Comment by vicfic** [comment]
Hemos creado la documentacion (javadoc), comentado el código y añadido el diagrama de clases.
