### ISSUE TITLE
Implementaciones de Anuncios, Canciones y Emisoras

### ISSUE THREAD

**Issue by srjavimoure** [heishiro-slash/VVS-Music#19]
Las implementaciones de contenido (Anuncios, Canciones y Emisoras) son listas de Contenido.

Si no existe una implementación que sea un elemento a secas, estaríais anidando listas de listas de listas...

El único modo de dar cierre a las listas sería creando un Contenido que fuese explicitamente una lista vacía de Contenidos pero no tendría sentido.

La forma de solucionar esto es, considerar las clases como: Cancion, Anuncio y Emisora.

Osea eliminar la lista de contenidos en Anuncio y Cancion pero mantener la lista de contenidos en Emisora ya que es la única que puede tener una lista de contenidos.

**Comment by faustinoco** [comment]
Arreglado
