### ISSUE TITLE
Buscar y listas vacías

### ISSUE THREAD

**Issue by andreu-barro** [heishiro-slash/VVS-Music#20]
No contempláis que, si un servidor no devolverá contenidos ante una búsqueda SIN token, devolverá una lista con un anuncio (el que se añade al principio), no será una lista vacía y por tanto no llamará a buscar en el servidor de respaldo, devolviendo la lista con un único anuncio.

**Comment by jmrio** [comment]
En principio este problema esta solucionado. 
Añadí una comprobación en la búsqueda que mira si el único contenido que esta en la lista es un anuncio.
