### ISSUE TITLE
Detalles generales

### ISSUE THREAD

**Issue by andreu-barro** [heishiro-slash/VVS-Music#21]
-ValidTokens en ServidorRespaldo no se usa nunca, borradla que ya la teneis en su clase padre.
-Los ArrayList no están tipados (ArrayList() en lugar de ArrayList<Contenido>(), por ejemplo).
-Imports que no se usan.
-En Token => caducidad = --caducidad; (o bien --caducidad o bien caducidad -= 1)

**Comment by jmrio** [comment]
-ValidTokens en ServidorRespaldo eliminado.
-Imports que no se usan eliminados.
-Sustituido --caducidad por caducidad-1.

No entiendo a que te refieres con lo de los ArrayList tipados, Si el Objeto List esta tipado no hace falta tipar el ArryList, ya que el IDE lo considera redundante.

**Comment by andreu-barro** [comment]
Pues a mi Eclipse me dice exactamente lo contrario. Me da este warning:
![foto](https://cloud.githubusercontent.com/assets/8897916/11132057/10ea41ba-898e-11e5-8527-c88ee6a3df6e.png)
Justamente la primera sugerencia de corrección me escribe el ArrayList<Contenido> automáticamente. Es a esto a lo que me refería con lo de tipar los ArrayList.

**Comment by jmrio** [comment]
Pues en Netbeans si lo tipas, te pone que es un tipado redundante, y te dice que si quieres tiparlo que le pongas ArrayList<>(), pero que no es obligatorio.

**Comment by jmrio** [comment]
Tras haberlo comentado con la profesora, opino que es un detalle sin importancia, ya que como dije antes, si el List es de un tipo se asume que el ArrayList es también del mismo tipo.

La solución que le he aplicado es Nombrar aplicar un tipado <> a todos los ArrayList().

**Comment by lauramcastro** [comment]
Nunca debedes informar de varios problemas nunha única issue, fai moi complexo o seguemento das cousas que se arreglan das que non, ademáis de que a xestión de unhas (bugs) non ten por que ser igual á das outras (help, invalid...).
