### ISSUE TITLE
Estruturación do proxecto: excepcións

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Music#25]
Non estou completamente dacordo co indicado na issue #16 por @srjavimoure de que todas as excepcións estean nun único paquete: tedes agora mezcladas excepcións que teñen que ver con Contidos con excepcións relacionadas cos Tokens, que pertencen de xeito natural a paquetes diferentes. Deberiades ter un utils.exceptions.contenido para as primeiras e utils.exceptions.tokens para as segundas.

**Comment by vicfic** [comment]
Issue arranxada
