### ISSUE TITLE
Uso de tipos concretos (especificación de Java Generics)

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Music#27]
A pesar da argumentación que leva ao peche da issue #21, no tocante ao tipado, e _independentemente do que diga un IDE ou outro_ (que non é un argumento, un IDE é software ao fin e ao cabo e pode conter erros!), como programadores e enxeñeiros, debemos saber que nas linguaxes con tipado estático convén utilizar sempre o tipo máis forte (concreto, restrinxido) posible, xa que isto obriga a un contrato máis explícito (desde o punto de vista das probas, concreta máis as particións equivalentes ao delimitar mellor o tipo). Polo tanto, é preferible utilizar ArrayList<Contenido> a ArrayList<>.

**Comment by jmrio** [comment]
Gracias pola aclaración. Arranxado.
